export {default as Navbar} from './Navbar/Navbar';
export {default as Footer} from './Footer/Footer';
export {default as Logo} from './Logo/Logo';
export {default as SocialMedia} from './SocialMedia/SocialMedia';
export {default as Button} from './Button/Button';
export {default as ButtonB} from './ButtonB/ButtonB';
export {default as Skill} from './Skill/Skill';
export {default as Service} from './Service/Service';
export {default as Project} from './Project/Project';